openapi: 3.0.2
info:
  version: 1.0.0
  title: CEX.IO API schema
  contact:
    email: marko.domic@outlook.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description: API schema of the CEX.IO REST API
# host: cex.io
# basePath: /api
# schemes: [ https ]
# produces: [ application/json ]
servers:
  - url: 'https://cex.io/api'
    description: CEX.IO API Server
paths:
  /tickers/{marketSymbol1}/{marketSymbol2}/{marketSymbol3}: 
    $ref: paths/tickers.yml
